### ISSUE TITLE
Can't use as Octokit with TypeScript

### ISSUE THREAD

**Issue by Maxim-Mazurok** [octokit/graphql.js#176]
I use Octokit like this:
```ts
import {Octokit} from '@octokit/rest';

export class Git {
  readonly octokit: Octokit;

  constructor(auth: string) {
    this.octokit = new Octokit({ auth });
  }
}
```

And I'd like to use graphql.js in a similar manner. But currently, `graphql` import is not of `graphql` type.
So, I have to use something like this:

```ts
import {graphql} from '@octokit/graphql';
import {graphql as Graphql} from '@octokit/graphql/dist-types/types';

export class Git {
  readonly graphql: Graphql;

  constructor(auth: string) {
    this.graphql = graphql.defaults({
      headers: {
        authorization: `token secret123`,
      },
    });
  }
}
```

It would be cool if they were more consistent.

**Comment by gr2m** [comment]
That should really not be necessary. The types are exported when you import `@octokit/graphql`, see https://unpkg.com/browse/@octokit/graphql@4.5.4/package.json#L51. Can you make sure you have the latest version?

Also I just want to make sure you are aware that `@octokit/rest` also exposes an `octokit.graphql()` method since v17 (since it's based on [`@octokit/core`](https://github.com/octokit/core.js)). So you might not need to import `@octokit/graphql` separately

**Comment by Maxim-Mazurok** [comment]
Thanks for your response.
Yes, I'm using the latest (`4.5.4`) version.
Still, I can't do something like this:
```ts
import {graphql as Graphql} from '@octokit/graphql';
class Git {
  readonly graphql: Graphql;
}
```

`octokit.graphql` works just fine for me without any additional imports, thanks!

**Comment by gr2m** [comment]
I'm not sure if there is something I can do about that, do you?

You'll have to do this for the time being

```ts
import {graphql} from '@octokit/graphql';
class Git {
  readonly graphql: typeof graphql;
}
```

**Comment by Maxim-Mazurok** [comment]
Yes, this also will definitely work!
I should've thought about `typeof`, nice solution 👍
