### ISSUE TITLE
variables aren't working

### ISSUE THREAD

**Issue by pthieu** [octokit/graphql.js#333]
I have this query:
```
    const res = await graphqlWithAuth(
      `
      query prData($user: String!) {
      search(query: "is:pr is:closed author:$user", type: ISSUE, first: 100) {
        edges {
          cursor
          node {
            ... on PullRequest {
              author {
                login
              }
              url
              title
              createdAt
              closedAt
              deletions
              additions
              merged
              state
              files(first: 100) {
                totalCount
                nodes {
                  additions
                  deletions
                  path
                }
              }
            }
          }
        }
      }
    }
    `,
      {
        user,
      },
    );
```

I get this response:
```
(node:83392) UnhandledPromiseRejectionWarning: GraphqlResponseError: Request failed due to following response errors:
 - Variable $user is declared by prData but not used
    at [/Users/pthieu/go/phong-commit-bot/node_modules/]()@octokit[/graphql/dist-node/index.js:81:13]()
    at processTicksAndRejections (internal[/process/task_queues.js:97:5]())
    at async getUserPulls ([/Users/pthieu/go/phong-commit-bot/index.js:194:17]())
    at async analyzeUser ([/Users/pthieu/go/phong-commit-bot/index.js:42:17]())
    at async Promise.all (index 0)
    at async main ([/Users/pthieu/go/phong-commit-bot/index.js:29:19]())
```

`user` is defined a bit before the query so it exists, I've also tried to hardcode a value. Format seems to be correct but the error keeps popping up.

If i completely remove variables and apply a hardcoded username after `author:`, it works, so the entire query should be structured properly.

**Comment by copperwall** [comment]
Hi @pthieu 👋 I believe this error is failing due to the GraphQL server following this section of the GraphQL spec about variable validation http://spec.graphql.org/October2021/#sec-All-Variables-Used. To the GraphQL server, I believe it views `"is:pr is:closed author:$user"` as a plain string and doesn't know that the `$user` section of the string is referencing the GraphQL variable supplied to your query. From looking at the GraphQL spec/docs it doesn't appear that the spec allows interpolating variables within a string

I believe the query should pass validation with the GraphQL server if the entire query is passed a variable and passed to the query argument on `search`, like

```graphql
query prData($query: String!) {
      search(query: $query, type: ISSUE, first: 100) {
```

**Comment by pthieu** [comment]
@copperwall ah that makes sense, I'll have to move my entire query to a variable, thanks!
