### ISSUE TITLE
Accidental release of `octokit-next.js` to `@octokit/graphql`

### ISSUE THREAD

**Issue by sheehan** [octokit/graphql.js#411]
The import from the readme quit working yesterday after version 2.3.0 was pushed. 

```html
<script type="module">
  import { graphql } from "https://cdn.skypack.dev/@octokit/graphql";
</script>
```
```
endpoint?from=@octokit-next/request:13 Uncaught Error: [Package Error] "@octokit-next/endpoint" no dependency version info found. (Imported by "@octokit-next/request").
    at endpoint?from=@octokit-next/request:13:7
```

I had to add `@5.0.1` to fix.

**Comment by wolfy1339** [comment]
That is interesting...
I have no idea where it's picking up the `@octokit-next/*` packages from, as they aren't used in this package at all.

**Comment by tmilewski** [comment]
"Downgrade" to 5.0.1. There was an accidental release, see #412.

**Comment by wolfy1339** [comment]
@gr2m Can you double check this?

**Comment by gr2m** [comment]
oh my very sorry for this, I'm looking into it

**Comment by gr2m** [comment]
To make sure this cannot happen again in future, I created a dedicated npm account for the `@octokit-next/*`. In a situation that occured here the release would simply fail, because the used NPM token belongs to https://www.npmjs.com/~octokit-next-bot and that user does not have access to the `@octokit/` scope at all.
